version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: orca-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orca
      MYSQL_USER: orca
      MYSQL_PASSWORD: orca
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
