name: WPF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # ajuste para sua versão

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar solução
        run: dotnet build --configuration Release --no-restore

      - name: Rodar testes
        run: dotnet test --configuration Release --no-build --verbosity normal
