name: ORCA CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar pacotes
      run: dotnet restore ORCA/ORCA.sln

    - name: Compilar solução
      run: dotnet build ORCA/ORCA.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Executar testes
      run: dotnet test ORCA.Testes/ORCA.Testes.csproj --configuration ${{ matrix.configuration }} --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Publicar resultados de teste
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: '**/TestResults/*.trx'

    - name: Publicar artefato (Build do ORCA)
      uses: actions/upload-artifact@v4
      with:
        name: ORCA-App
        path: ORCA/bin/${{ matrix.configuration }}/net8.0-windows/**
