name: ORCA CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest

    env:
      # 🔹 String de conexão ao banco da nuvem
      ConnectionStrings__Default: "Server=srv1889.hstgr.io;Port=3306;Database=u202947255_orca;User ID=u202947255_root;Password=TCCorca123;SslMode=none;"
      Solution_Name: ORCA.sln
      Test_Project_Path: ORCA.Testes/ORCA.Testes.csproj

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar dependências
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Rodar apenas testes
      run: dotnet test ${{ env.Test_Project_Path }} --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

    - name: Publicar resultados dos testes
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults
