name: ORCA CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: banco
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      Solution_Name: ORCA/ORCA.sln
      Test_Project_Path: ORCA/ORCA.Testes/ORCA.Testes.csproj

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Aguardar MySQL iniciar
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL está pronto!"
              break
            fi
            echo "Aguardando MySQL..."
            sleep 2
          done

      - name: Criar tabela e inserir dados fake
        run: |
          mysql -h127.0.0.1 -uroot -proot banco <<'EOF'
          CREATE TABLE IF NOT EXISTS usuario (
            id INT AUTO_INCREMENT PRIMARY KEY,
            email TEXT,
            senha VARCHAR(255),
            permissao VARCHAR(3)
          );

          INSERT INTO usuario (email, senha, permissao) VALUES
            ('yslan_adm@gmail.com', '123', 'adm'),
            ('yslan_usr@gmail.com', '123', 'usr'),
            ('yslan_ges@gmail.com', '123', 'ges');
          EOF

      - name: Debug - Listar estrutura de pastas
        run: ls -R

      - name: Restaurar dependências
        run: dotnet restore $Solution_Name

      - name: Debug - Listar estrutura de pastas (após restore)
        run: ls -R

      - name: Rodar testes
        run: dotnet test $Test_Project_Path --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
