name: Build ORCA Installer

on:
  release:
    types: [published]   # dispara quando você publica um release

permissions:
  contents: write   # necessário para anexar arquivo ao release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Get version from tag
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $env:GITHUB_OUTPUT

      - name: Build installer
        run: |
          iscc setup.iss /dMyAppVersion=${{ steps.get_version.outputs.version }}

      - name: Upload installer to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist\ORCA_Installer_*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
