name: Build ORCA Installer

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build and publish .NET app
        run: dotnet publish ORCA/ORCA.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Setup Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $env:GITHUB_OUTPUT

      - name: Build installer
        run: iscc setup.iss /dMyAppVersion=${{ steps.get_version.outputs.version }}

      - name: List dist folder (debug)
        run: dir dist

      - name: List publish folder (debug)
        run: dir publish

      - name: Upload installer to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ORCA_Installer_*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
