name: Build ORCA Release

on:
  push:
    tags:
      - 'v*'   # roda sempre que criar uma tag do tipo v1.0.0, v2.0.1 etc

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # ou a versão que seu projeto usa

      - name: Restaurar dependências
        run: dotnet restore ./ORCA/ORCA.csproj

      - name: Build Release
        run: dotnet publish ./ORCA/ORCA.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o out

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: ORCA
          path: out/
