name: Build & Release ORCA (Two Packages)

on:
  release:
    types: [published]   # dispara quando você publica um release manualmente

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version from release tag
        id: getver
        shell: pwsh
        run: |
          $v = "${{ github.ref_name }}"
          if ($v.StartsWith("v")) { $v = $v.Substring(1) }
          echo "version=$v" >> $env:GITHUB_OUTPUT

      # --- Build Framework Dependent ---
      - name: Publish (framework dependent)
        run: |
          dotnet restore ORCA/ORCA.csproj
          dotnet publish ORCA/ORCA.csproj -c Release -r win-x64 --self-contained false -o publish-fx

      - name: Zip framework dependent build
        run: |
          Compress-Archive -Path publish-fx\* -DestinationPath ORCA-win-x64-${{ steps.getver.outputs.version }}.zip

      # --- Build Self-Contained ---
      - name: Publish (self-contained)
        run: |
          dotnet publish ORCA/ORCA.csproj -c Release -r win-x64 --self-contained true -o publish-sc

      - name: Zip self-contained build
        run: |
          Compress-Archive -Path publish-sc\* -DestinationPath ORCA-win-x64-selfcontained-${{ steps.getver.outputs.version }}.zip

      # --- Upload como artefatos ---
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ORCA-Binaries
          path: |
            ORCA-win-x64-${{ steps.getver.outputs.version }}.zip
            ORCA-win-x64-selfcontained-${{ steps.getver.outputs.version }}.zip

      # --- Anexar ao Release existente ---
      - name: Attach zips to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ORCA-win-x64-${{ steps.getver.outputs.version }}.zip
            ORCA-win-x64-selfcontained-${{ steps.getver.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
