name: Build and Release ORCA

on:
  release:
    types: [published] # roda só quando criamos um release no GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ORCA/ORCA.csproj

      - name: Build solution
        run: dotnet build ORCA/ORCA.csproj --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish ORCA/ORCA.csproj -c Release -o out /p:Platform="AnyCPU"

      # Etapa de empacotamento MSIX
      - name: Package MSIX
        run: |
          mkdir msix
          # Aqui você pode rodar o MSIX Packaging Tool via linha de comando (makeappx.exe)
          makeappx pack /d out /p msix/ORCA.msix

      # Upload do MSIX para o Release atual
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: msix/ORCA.msix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
