name: Build & Release ORCA (Artifact Only)

on:
  push:
    tags:
      - "v*"   # dispara quando você cria uma tag tipo v1.2.3

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore & Publish (WPF)
        run: |
          dotnet restore ORCA/ORCA.csproj
          dotnet publish ORCA/ORCA.csproj -c Release -r win-x64 --self-contained false -o publish

      - name: Get version from tag (strip leading v)
        id: getver
        shell: pwsh
        run: |
          $v = "${{ github.ref_name }}"
          if ($v.StartsWith("v")) { $v = $v.Substring(1) }
          echo "version=$v" >> $env:GITHUB_OUTPUT

      - name: Zip published files
        run: |
          Compress-Archive -Path publish\* -DestinationPath ORCA-${{ steps.getver.outputs.version }}.zip

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: ORCA-Binaries
          path: ORCA-${{ steps.getver.outputs.version }}.zip

      - name: Create GitHub Release and attach zip
        uses: softprops/action-gh-release@v2
        with:
          name: ORCA v${{ steps.getver.outputs.version }}
          files: ORCA-${{ steps.getver.outputs.version }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
