name: Release ORCA

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore ORCA/ORCA.csproj

      - name: Build projeto
        run: dotnet build ORCA/ORCA.csproj -c Release --no-restore

      - name: Publicar binários
        run: dotnet publish ORCA/ORCA.csproj -c Release -o out

      # Criação do pacote MSIX com MSIX Packaging Tool
      - name: Instalar MSIX Packaging Tool
        run: choco install microsoft.msixsdk -y

      - name: Empacotar em MSIX
        run: |
          mkdir package
          MakeAppx pack /d out /p package/ORCA.msix /l

      # Assinar o pacote (precisa de certificado válido)
      # Exemplo usando secrets
      - name: Importar certificado
        run: |
          echo "${{ secrets.SIGN_CERT_PFX }}" | base64 -d > cert.pfx
          certutil -f -p "${{ secrets.SIGN_CERT_PASS }}" -importpfx cert.pfx

      - name: Assinar MSIX
        run: |
          signtool sign /fd SHA256 /a /f cert.pfx /p "${{ secrets.SIGN_CERT_PASS }}" package/ORCA.msix

      - name: Upload para o Release
        uses: softprops/action-gh-release@v1
        with:
          files: package/ORCA.msix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
